## setwd, modify according to your needs

setwd("~/OneDrive/TopicModellingR/GreekTM")

### Load Data generated by GreekTM.R

load("~/OneDrive/TopicModellingR/GreekTM/backup.RData")

### more experiments // very experimental and not made for speedy processing

test_matrix2 <- matrix(nrow=length(corpus[,1]), ncol = length(corpus[,1]))
rownames(test_matrix2) <- corpus[,1]
colnames(test_matrix2) <- corpus[,1]

is_similar2 <- function(x,y) {
  check <- all.equal(theta.frame[which(theta.frame[,1] == x),], theta.frame[which(theta.frame[,1] == y),]) # comparing with all.equal
  check2 <- all.equal(theta.frame[which(theta.frame[,1] == y),], theta.frame[which(theta.frame[,1] == x),]) # comparing with all.equal
  if (length(check) == 1) {if (check == TRUE) {
    result <- 0
    return(result)
  }}
  result1 <- mean(as.numeric(sub(".*?difference: (.*?)", "\\1", check)[3:length(check)]))
  result2 <- mean(as.numeric(sub(".*?difference: (.*?)", "\\1", check2)[3:length(check2)]))
  result <- (result1 + result2) / 2
  return(result)}

### It crawls to build the matrix: around 12h for Thucydides on MacBookPro, 8GB
### Don't execute, unless you really want it

t1 <- Sys.time()
for (i in corpus[,1][1:2]) {
  for (j in corpus[,1][1:2]) {
    test_matrix2[which(corpus[,1] == i), which(corpus[,1] == j)] <- is_similar2(i,j)
  }
}
t2 <- Sys.time()
time_testing_similarity <- t2 - t1
time_testing_similarity