## setwd, modify according to your needs

setwd("~/OneDrive/TopicModellingR/LatinTM")

### Load Data generated by GenerateTestMatrix.R

# load("~/OneDrive/TopicModellingR/GreekTM/backup.RData")

smallest_notZeroNA <- apply(na.omit(test_matrix), 1, FUN = function(x) {min(x[x > 0])})
similarSentences <- which(test_matrix <= max(smallest_notZeroNA) & test_matrix > 0 , arr.ind=T )

sightreading <- function(x,y) {
  i <- which(colnames(test_matrix) == x)
  sight_names <- names(head(sort(test_matrix[names(which(similarSentences[,2] == i)), i]), n=y))
  return(sight_names)
}

find_start <- function(x) {
  start_slice <- which(colnames(test_matrix) == x) - 1
  if (start_slice == 0) {return(which(colnames(test_matrix) == x))}
  return(start_slice)
}

find_end <- function(x) {
  end_slice <- which(colnames(test_matrix) == x) + 1
  if (end_slice == length(colnames(test_matrix))+1) {return(which(colnames(test_matrix) == x))}
  return(end_slice)
}

neighbours <- function(x) {
  base <- which(colnames(test_matrix) == x)
  if (base + 1 == length(colnames(test_matrix))+1) {
    right_neighbour <- base
  }
  else {
    right_neighbour <- base + 1
  }
  if (base - 1 == 0) {
    left_neighbour <- base
  }
  else {
    left_neighbour <- base - 1
  }
  return(c(left_neighbour, base, right_neighbour))
}

visualise_similarity <- function(x, y) {
  sightreadings <- sightreading(x, y)
  passages <- as.vector(unname(sapply(sightreadings, neighbours)))
  matrix_slice <- test_matrix[passages, find_start(x):find_end(x)]
  matrix_slice <- matrix_slice[order(rownames(matrix_slice)),]
  d3heatmap(matrix_slice, dendrogram = "none", color = "Blues", anim_duration = 0, xaxis_font_size = 12, yaxis_font_size = 12)
}

# unordered

extract_sentences <- function(x) {
  similar_sentences.list <- list(corpus[which(corpus[,1] == x), 1], corpus[which(corpus[,1] == x), 2], corpus_parsed[which(corpus_parsed[,1] == x), 2])
  return(similar_sentences.list)
}

base_parsed <- vector()
for (i in base){
  base_parsed[[i]] <- unname(corpus_parsed[which(corpus_parsed == i),][2])
}
base_parsed <- paste(unname(base_parsed), sep="", collapse = " ")
base_parsed <- unique(unlist(strsplit(base_parsed, "[[:space:]]+")))

sight_passages <- function(x, y) {
  similar_sentences <- sightreading(x, y)
  similar_sentences.df <- sapply(similar_sentences, extract_sentences)
  similar_sentences.df <- t(similar_sentences.df)
  similar_sentences.df <- as.data.frame(similar_sentences.df)
  colnames(similar_sentences.df) <- c(x, corpus[which(corpus == x), 2], corpus_parsed[which(corpus_parsed == x), 2])
  for (i in 1:length(similar_sentences.df[,3])){
    comparison <- unlist(strsplit(as.character(similar_sentences.df[i,3]), "[[:space:]]+"))
    similar_sentences.df[i,4] <- as.character(paste(comparison %in% base_parsed, sep="", collapse = " "))
    position_parsed <- which(unlist(strsplit(as.character(similar_sentences.df[i,4]), "[[:space:]]+")) == TRUE)
    position_notparsed <- which(unlist(strsplit(as.character(similar_sentences.df[i,4]), "[[:space:]]+")) == FALSE)
    text_vector <- unlist(strsplit(paste(similar_sentences.df[i,2], sep = "", collapse = " "), "[[:space:]]+"))
    text_vector[position_parsed] <- paste("**", text_vector[position_parsed], "**", sep="")
    text_vector[position_notparsed] <- paste("[", text_vector[position_notparsed], "]", "(http://www.perseus.tufts.edu/hopper/morph?l=", text_vector[position_notparsed], "&la=greek#lexicon)", sep="")
    similar_sentences.df[i,5] <-paste(text_vector, sep="", collapse=" ") 
    similar_sentences.df[i,6] <- unname(table(comparison %in% base_parsed)["TRUE"])/(unname(table(comparison %in% base_parsed)["TRUE"])+unname(table(comparison %in% base_parsed)["FALSE"]))*100
  }
  
  colnames(similar_sentences.df)[4] <- "Word from base sentence?"
  colnames(similar_sentences.df)[5] <- "Position known word"
  colnames(similar_sentences.df)[6] <- "Percent known"
  similar_sentences.frame <- data.frame(unname(unlist(similar_sentences.df[,1])),
                                        unname(unlist(similar_sentences.df[,5])),
                                        unname(unlist(similar_sentences.df[,6])))
  colnames(similar_sentences.frame) <- c(colnames(similar_sentences.df[1]), colnames(similar_sentences.df[2]), colnames(similar_sentences.df[6]))
  filepath <- paste('LatinumB_tab/', x, '.md', sep="")
  write.table(similar_sentences.frame, file = filepath, append = FALSE, quote = FALSE, sep = "<br>\n", eol = "<br><br>\n", na = "NA", dec = ".", row.names = FALSE, col.names = TRUE)
}

# example

test_matrix <- test_matrix2
sight_passages("LatinumB:23.1", 5)
visualise_similarity("LatinumB:23.1", 5)
